services:
  - type: web
    name: slot-managment
    runtime: docker
    dockerfilePath: ./Dockerfile

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "False"

      - key: DJANGO_ALLOWED_HOSTS
        sync: false

      - key: SECURE_SSL_REDIRECT
        value: "True"

      - key: SECURE_HSTS_SECONDS
        value: "31536000"